#! /bin/bash -eu

cd $(dirname $0)/..

VERSION=$(date +'%Y%m%d%H%M')
IMAGE_NAME=node-hello-world
DOCKER_IMAGE=mali09tian/${IMAGE_NAME}

docker build -t ${IMAGE_NAME}:build .

# Release to new registry
docker tag ${IMAGE_NAME}:build ${DOCKER_IMAGE}:${VERSION}
docker tag ${IMAGE_NAME}:build ${DOCKER_IMAGE}:latest
